plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.sprint.mission'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

// railway 에서 자바 버전인식을 위한 항목.
// railway 배포시에는 위의 java{} 블럭을 주석처리하고 아래의 항목 주석을 풀 것.
//sourceCompatibility = '17'
//targetCompatibility = '17'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.16'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'org.postgresql:postgresql'
	testCompileOnly 'org.projectlombok:lombok'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testAnnotationProcessor 'org.projectlombok:lombok'
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	runtimeOnly 'com.h2database:h2'
}

tasks.named('test') {
	useJUnitPlatform()
}

// for build .jar file to test
//bootJar {
//	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
//	destinationDirectory = file("/home/latte/test")
//	archiveFileName = "discodeit.jar"
//}

// railway 배포를 위한 boot.jar 항목
// railway 설정에서 deploy -> start commend 에 build/libs/app.jar 이라 시작커맨드로 명확히 할 것.
//bootJar {
//	enabled = true
//	archiveFileName = 'app.jar'
//}
//jar {
//	enabled = false // plain.jar 생성을 막아 Railway가 헷갈리지 않게 합니다.
//}