services:

  # PostgreSQL
  db:
    image: postgres:16

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      # PostgreSQL 데이터 유지
      - pgdata:/var/lib/postgresql/data

      # DB 최초 생성 시 schema.sql 자동 실행
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 10

    networks:
      - app-network


  # Discodeit 애플리케이션
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

    # DB가 정상적으로 준비된 후 app 실행
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "8081:8080"

    # BinaryContentStorage 데이터 유지
    volumes:
      - binary-data:/app/upload-files

    networks:
      - app-network


# Named Volumes
volumes:
  pgdata:
  binary-data:


# Network
networks:
  app-network: