name: discodeit

services:
  postgres:
    image: postgres:16
    container_name: discodeit-postgres
    restart: unless-stopped

    ports:
      - ${POSTGRES_HOST_PORT}:5432

    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: ${TZ}

    volumes:
      - discodeit-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL","pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"
        ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - app-network

  app:
    build:
      context: .
      args:
        PROJECT_NAME: ${PROJECT_NAME}
        PROJECT_VERSION: ${PROJECT_VERSION}
      dockerfile: Dockerfile
    ports:
      - 8081:${SERVER_PORT}
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SERVER_PORT: ${SERVER_PORT}
      STORAGE_LOCAL_ROOT_PATH: /app/storage
      STORAGE_TYPE: ${STORAGE_TYPE}
      JVM_OPTS: ${JVM_OPTS}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      AWS_S3_REGION: ${AWS_S3_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_S3_PRESIGNED_URL_EXPIRATION: ${AWS_S3_PRESIGNED_URL_EXPIRATION}
      ADMIN_USER_NAME: ${ADMIN_USER_NAME}
      ADMIN_USER_PASSWORD: ${ADMIN_USER_PASSWORD}
      ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL}
      REMEMBER_ME_KEY: ${REMEMBER_ME_KEY}

    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - binary-data:/app/storage

volumes:
  discodeit-postgres-data:
  binary-data:

networks:
  app-network:
    driver: bridge
