spring:
  application:
    name: discodeit

  profiles:
    active: dev

discodeit:
  storage:
    type: local
    local:
      root-path: ./storage

logging:
  level:
    root: info

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

  api-docs:
    path: /my-api