spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  # .sql 파일을 이용하지 않고, hibernate 가 DDL 을 작성하도록 설정.
  sql:
    init:
      mode: never

  # Spring admin 클라이언트 등록용 설정.
#  boot:
#    admin:
#      client:
#        url: http://localhost:9090


logging:
  level:
    com.sprint.mission.discodeit: debug
    org.hiberate.SQL: INFO
    org.hibernate.orm.jdbc.bind: INFO