spring:
  application:
    name: discodeit

  profiles:
    active: dev   # 로컬 기본 프로파일. 배포 시 -Dspring.profiles.active=prod 로 덮어씀

  jpa: #SQL로그 확인 + 테이블 자동 생성 방지(요구사항: DDL을 직접 작성하고 schema.sql에 포함하세요)
    hibernate:
      ddl-auto: validate        # schema.sql로 테이블 직접 관리할 거라 validate
    show-sql: true              # SQL 로그 출력
    properties:
      hibernate:
        format_sql: true        # SQL 보기 좋게 포맷
        use_sql_comments: true  # 어떤 쿼리인지 주석 표시
    open-in-view: false         # OSIV 비활성화(요구사항임)

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

discodeit:
  repository:
    type: file
    file-directory: .discodeit
  storage:
    type: local  #← @ConditionalOnProperty가 이걸 보고 Bean 등록 여부 결정
    local:
      root-path: .storage #← @Value가 이걸 가져와서 root 필드에 할당

info:
  app:
    name: Discodeit
    version: 1.7.0
    java:
      version: 17
    spring-boot:
      version: 3.4.0
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}
  storage:
    type: ${discodeit.storage.type}
    path: ${discodeit.storage.local.root-path}
  multipart:
    max-file-size: ${spring.servlet.multipart.max-file-size}
    max-request-size: ${spring.servlet.multipart.max-request-size}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: info # 기본 로깅 레벨