spring:
  application:
    name: discodeit

server:
  port: 8080

# application.yaml
discodeit:
  repository:
    # type: file   # jcf(메모리에 저장) | file(파일에 저장)
  type: jcf
  storage:
    root-path: file-data-map
    extension: .ser