spring:
  application:
    name: discodeit

  profiles:
    active: dev


discodeit:
  repository:
    type: file
    file-directory: .discodeit

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    display-request-duration: true
    doc-expansion: none

  api-docs:
    path: /my-api